---
name: Tests
on: [ push, pull_request ]
jobs:
  test:
    name: Test (Ruby ${{ matrix.ruby }})
    runs-on: ubuntu-${{ matrix.ubuntu }}
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.3', '2.4', '2.5', '2.6', '2.7', '3.0', '3.1', '3.2', '3.3', 'jruby', 'truffleruby' ]
        ubuntu: [ latest ]
        include:
          - { ruby: '2.0', ubuntu: '20.04' }
          - { ruby: '2.1', ubuntu: '20.04' }
          - { ruby: '2.2', ubuntu: '20.04' }
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake
